[server]
maxUploadSize = 500

[theme]
base = "dark"
primaryColor = "#A995FF"
backgroundColor = "#090C15"
secondaryBackgroundColor = "#171D30"
textColor = "#F6F7FB"
font = "sans serif"

[browser]
gatherUsageStats = false
